"""renamed tables and added script_params table

Revision ID: 09a713716b1a
Revises: d022c17379ac
Create Date: 2020-08-27 15:26:32.702508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a713716b1a'
down_revision = 'd022c17379ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_links',
    sa.Column('directoryPath', sa.String(), nullable=True),
    sa.Column('scriptPath', sa.String(), nullable=True),
    sa.Column('dataType', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('samples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('formula', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('starred', sa.Boolean(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script_params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=True),
    sa.Column('paramName', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('valueType', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('data_link')
    op.drop_table('sample')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('formula', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('starred', sa.BOOLEAN(), nullable=True),
    sa.Column('project', sa.VARCHAR(), nullable=True),
    sa.CheckConstraint('starred IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_link',
    sa.Column('directoryPath', sa.VARCHAR(), nullable=True),
    sa.Column('scriptPath', sa.VARCHAR(), nullable=True),
    sa.Column('dataType', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.drop_table('script_params')
    op.drop_table('samples')
    op.drop_table('data_links')
    # ### end Alembic commands ###
