"""added project column to sample table

Revision ID: 355390c313e9
Revises: a26d8f43db25
Create Date: 2020-08-13 12:20:14.198485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355390c313e9'
down_revision = 'a26d8f43db25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('project', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'project')
    # ### end Alembic commands ###
