"""DataLink table

Revision ID: 936d6d955d42
Revises: 355390c313e9
Create Date: 2020-08-21 16:23:09.003344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936d6d955d42'
down_revision = '355390c313e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_link',
    sa.Column('directoryPath', sa.String(), nullable=True),
    sa.Column('scriptPath', sa.String(), nullable=True),
    sa.Column('dataType', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_link')
    # ### end Alembic commands ###
