"""changed title to name in Datalink

Revision ID: ab84de07a19a
Revises: 936d6d955d42
Create Date: 2020-08-25 20:19:27.381500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab84de07a19a'
down_revision = '936d6d955d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_link', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('data_link', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_link', sa.Column('title', sa.VARCHAR(), nullable=False))
    op.drop_column('data_link', 'name')
    # ### end Alembic commands ###
