"""empty message

Revision ID: d022c17379ac
Revises: ab84de07a19a
Create Date: 2020-08-25 20:33:21.964653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd022c17379ac'
down_revision = 'ab84de07a19a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_link',
    sa.Column('directoryPath', sa.String(), nullable=True),
    sa.Column('scriptPath', sa.String(), nullable=True),
    sa.Column('dataType', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_link')
    # ### end Alembic commands ###
